version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobtracker-postgres
    restart: always
    environment:
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: jobtracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
